server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Server
  datasource:
    url: "jdbc:mysql://localhost:3306/android"
    username: root
    password: 10040109
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
