server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Server
  datasource:
    url: "jdbc:mysql://localhost:3306/android"
    username: test_user
    password: Test_user123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
